name: Build binary rule-set and config
on:
  push:
    paths:
      - .github/workflows/build.yml
      - geosite-audit.yml
      - geosite-audit_doh.yml
      - index-src.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - name: Build
      run: |
        cd ~
        wget https://github.com/SagerNet/sing-box/releases/download/v1.10.0-alpha.22/sing-box_1.10.0-alpha.22_linux_amd64.deb
        sudo dpkg -i sing-box_1.10.0-alpha.22_linux_amd64.deb
        cd -
        for filename in geosite-audit geosite-audit_doh; do
          yq -o=json $filename.yml >$filename.json
          sing-box rule-set compile $filename.json
        done
        yq eval-all '. as $item ireduce ({}; . *+ $item )' index-src.yml inbounds-tun.yml >index.yml
    - name: Commit files
      run: |
        git add .
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "Build binary rule-set and config"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.head_ref }}
